# DOCKER DEPLOY CODE BASICS

# Use official Python image
FROM python:3.9-slim

# Set working directory inside container
WORKDIR /app

# Copy requirements.txt first (better for caching)
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project
COPY . .

# Expose port for Flask app
EXPOSE 5000

# Run the Flask app
CMD ["python", "app/app.py"]
