name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]   # change if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set up Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: harishv11/ai-with-mechanics
        tags: |
          type=sha
          type=ref,event=branch
          type=raw,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
